# Generated by Django 3.0.4 on 2020-04-23 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='facebook',
            field=models.URLField(default=''),
        ),
        migrations.AddField(
            model_name='profile',
            name='instagram',
            field=models.URLField(default=''),
        ),
        migrations.AddField(
            model_name='profile',
            name='twitter',
            field=models.URLField(default=''),
        ),
    ]
