# Generated by Django 2.0.12 on 2020-05-01 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hscnumber',
            name='cgst',
            field=models.FloatField(verbose_name='Други добавки (в %)'),
        ),
        migrations.AlterField(
            model_name='hscnumber',
            name='hsc_number',
            field=models.CharField(max_length=200, verbose_name='Код на данък'),
        ),
        migrations.AlterField(
            model_name='hscnumber',
            name='sgst',
            field=models.FloatField(verbose_name='ДДС (в %)'),
        ),
        migrations.AlterField(
            model_name='work',
            name='amount',
            field=models.FloatField(verbose_name='Цена (без ДДС)'),
        ),
        migrations.AlterField(
            model_name='work',
            name='code',
            field=models.CharField(max_length=200, unique=True, verbose_name='Код на услугата'),
        ),
        migrations.AlterField(
            model_name='work',
            name='jc_number',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Номер на транзакция'),
        ),
        migrations.AlterField(
            model_name='work',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='work',
            name='po_number',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Номер на услуга'),
        ),
    ]
