# Generated by Django 3.0.4 on 2020-04-08 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_page'),
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('service_type', models.CharField(choices=[('service', 'Услуга'), ('haircut', 'Прическа')], default='service', max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('service_icon', models.CharField(choices=[('spray', 'Боадисване'), ('dryer', 'Сешуар'), ('barber', 'Подстригване'), ('location', 'Услуга на адрес'), ('razor', 'Бръснар')], default='barber', max_length=20)),
                ('image', models.ImageField(default='default_service.jpg', upload_to='service_pics')),
            ],
        ),
    ]
