# Generated by Django 3.0.4 on 2020-04-13 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_services'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='price',
            field=models.FloatField(default=0),
        ),
    ]
